import Head from "next/head";
import styles from "../styles/Home.module.css";
import Featured from "../components/Featured";
import PizzaList from "../components/PizzaList";
import axios from "axios";

export default function Home({ products }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Jonie Pizza Restaurant</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Featured />
			<PizzaList products={products} />
		</div>
	);
}

export const getServerSideProps = async () => {
	const res = await axios.get("http://localhost:3000/api/products");

	return {
		props: {
			products: res.data,
		},
	};
};
